### ISSUE TITLE
Suggestion: different tab styles

### ISSUE THREAD

**Issue by Draylar** [vini2003/Spinnery#10]
I think it would be good to have several tab variants/styles. For reference, the current tab design is:
![image](https://user-images.githubusercontent.com/17728338/73127953-b0f4e700-3f8d-11ea-9dd4-99a2a18a840d.png)

A few alternatives could be:
**Miniature-left:**

![](https://i.imgur.com/JZk82x4.png)

**Miniature-middle:**

![](https://i.imgur.com/vqAw3sk.png)

Another idea is hover prompts... excuse the horrible edit.

![](https://i.imgur.com/W4eJt0b.png)

**Comment by JerwuQu** [comment]
I think having the active tab blend in with the window would be nice as well

![tab](https://user-images.githubusercontent.com/3710677/75560889-5516f580-5a46-11ea-84aa-1543445ccd37.png)

**Comment by vini2003** [comment]
It's only been four months, but I've finally gotten around to miniature icons.

**Comment by vini2003** [comment]
Fixed rendering in 3.0.56, native tooltip support with overrides for now; will add setters soon.
