### ISSUE TITLE
You can't hold down the arrow/backspace in WDynamicText

### ISSUE THREAD

**Issue by ghost** [vini2003/Spinnery#14]
If you try to hold down one of the horizontal arrow keys or the backspace, it only happens once and won't happen again, it seems like it only happens with client-side screens, but i didn't check it here. Also LibGUI is affected by the [very same bug](https://github.com/CottonMC/LibGui/issues/27), so it might be a vanilla-related problem?

**Comment by vini2003** [comment]
Yes you can, but it breaks seemingly randomly. Up to this day I have no idea why. It does seem to be a vanilla issue though.
