### ISSUE TITLE
General weirdness with text selection in WDynamicText

### ISSUE THREAD

**Issue by ghost** [vini2003/Spinnery#17]
There's multiple issues with text selection specifically.

If you write 2 characters, go to the beginning of the text and then press SHIFT + Right Arrow, it will somehow select 2 characters instead of just a single one.
If you do select everything with CTRL + A and then copy/cut it, the last character will be missing when you paste it.
You can also quickly [crash the game](https://gist.github.com/joaoh1/86e9196c1966a6af070c05c41cbebe73) when you type a single letter, select it with SHIFT + Left Arrow then CTRL + X it.

**Comment by vini2003** [comment]
I need to rewrite it. It sucks.
