### ISSUE TITLE
Title parameter in BaseContainerScreen's constructor is ignored

### ISSUE THREAD

**Issue by Juuxel** [vini2003/Spinnery#21]
`BaseContainerScreen` doesn't render the title, so it's useless. It should probably pass `new LiteralText("")` in the super call, or actually do something with the title.

**Comment by vini2003** [comment]
that's master for you, heh

i shall fix, probably in the weekend with how things are going

**Comment by vini2003** [comment]
turns out it's not ignored; it's used for the narrator, but that's it. it's a general screen name. it'll continue being worthless but have to be passed if you want to support narrator.

**Comment by Juuxel** [comment]
Do Spinnery widgets even support the narrator in general, like vanilla buttons etc?

(I think you have to make them the screen's child elements for that to work)
