### ISSUE TITLE
Froge 1.7 pls

### ISSUE THREAD

**Issue by Ueaj-Kerman** [vini2003/Spinnery#25]
I ned this for my froge mod emerald tools, can u mae ir work wit mccreator?

**Comment by Shrimpstress** [comment]
e

**Comment by vini2003** [comment]
yis i can but ned three number on back of mom credit cad, big numbers 16 on back, the data, and expire data. thank.

**Comment by Ueaj-Kerman** [comment]
Tanks u, sry 4 bad englis
