### ISSUE TITLE
elements should block children from rendering outside of its bounds

### ISSUE THREAD

**Issue by Martmists-GH** [vini2003/Spinnery#28]
This can be achieved with glScissor and related methods/constants, though I don't have a working implementation.

**Comment by vini2003** [comment]
no

**Comment by Martmists-GH** [comment]
yes

**Comment by vini2003** [comment]
no

**Comment by vini2003** [comment]
learn to use glscissors or something

**Comment by vini2003** [comment]
yes

**Comment by vini2003** [comment]
actually no, would require much more work than scissoring, because gl is a dumb state machine

**Comment by Martmists-GH** [comment]
KEKW
