### ISSUE TITLE
1.15 Version using 1.16 Fabric API?

### ISSUE THREAD

**Issue by ghost** [vini2003/Spinnery#54]
The .POM file on the maven specifies version `0.6.2+build.327-1.16` for the Fabric API.
![image](https://user-images.githubusercontent.com/47482177/82508860-5d764e00-9ad4-11ea-9cce-8ae82fd09333.png)

**Comment by ghost** [comment]
I'm specifically using `2.0.35+fabric-1.15.2` of Spinnery

**Comment by vini2003** [comment]
That seems very wrong indeed. I am sorry for the delay, had a quick burnout.

**Comment by vini2003** [comment]
Working on `WVerticalScrollableContainer`, will shortly port changes to `WHorizontalScrollableContainer`, iron out issues and release an updated and fixed build.
