### ISSUE TITLE
Slots render count of stacks with 1 item

### ISSUE THREAD

**Issue by Draylar** [vini2003/Spinnery#6]
In vanilla, a stack with a count of 1 in a slot doesn't have a rendered count label.
![image](https://user-images.githubusercontent.com/17728338/73127459-22309c00-3f86-11ea-959c-2a43952e7cac.png)

In Spinnery, the count is still rendered:
![image](https://user-images.githubusercontent.com/17728338/73127467-37a5c600-3f86-11ea-8062-16e442509292.png)

**Spinnery Version**: 0ac6149bd2

**Comment by vini2003** [comment]
It's a *feature*.

~~Will fix.~~
