### ISSUE TITLE
1.16.1 Crash when Spinnery loads a world

### ISSUE THREAD

**Issue by furtabs** [vini2003/Spinnery#67]
Tried using the standalone and a baked jar in a mod that uses Spinnery and cant find any info. No clue what mod is causing this fully but help is wanted.

https://gist.github.com/CrankySupertoon/dc94555d6cf2ab61a082f508cf93bc92

**Comment by bessiq** [comment]
Just happened to me, too. But in my case, Spinnery works fine by itself. Disabling the Clippy's Tippies mod (which requires Spinnery) allowed the world to load properly. WHY CLIPPY

**Comment by vini2003** [comment]
Fixed in 3.0.56.
