### ISSUE TITLE
Standard mouse actions/gestures don't work with WSlots

### ISSUE THREAD

**Issue by Draylar** [vini2003/Spinnery#8]
In vanilla, there are a few useful mouse actions & gestures that are usable in most inventories. The following example video covers, in order:
 - right-click single spreading
 - left-click stacks spreading (with even distribution)
 - double-click "collect all of held type"

[![Vanilla](https://i.imgur.com/rkdGfLE.png)](https://streamable.com/jii9q#)

WSlots do not follow the same behavior, as shown in the following video (same order):

[![Vanilla](https://i.imgur.com/G9lTgj8.png)](https://streamable.com/1qdeq)

**Comment by vini2003** [comment]
yes, this is something i tried to implement but ended up too cursed. i plan on fixing it.
