### ISSUE TITLE
Shift clicking with WSlots

### ISSUE THREAD

**Issue by Draylar** [vini2003/Spinnery#9]
Left separate from #8 because the fix & discussion will most likely go a little bit differently.

**Issue:**
In vanilla, shift-left-clicking a slot will transfer all items in it to a slot on the other side of the inventory. From what I can tell, this same functionality doesn't exist with WSlots.

**Solutions:**
 The main issue is deciding where a slot should send items to (or where the "other side" is). A couple of ideas could be:
 - having a default behavior (eg. opposite inventory ID, first slot) with overrideable behavior
 - having priority or indexes for collections of slots as a whole
 - using vanilla behavior (not sure if this would work with the custom slots, though, and it's my understanding it can bug out)

**Requirements:**
Ideally, shift-clicking would cover the normal functionality of:
 - merging into existing stacks
 - moving to the opposite side
 - sending to "best fit" slot (eg. fuel -> furnace fuel slot, ore -> furnace burn slot)

**Comment by vini2003** [comment]
it currently sends them to the first other inventory in the list. needs improving, of course.

**Comment by Draylar** [comment]
Ahh, sorry about that. For some reason, it wasn't working previously (but is now working).
